# Generated by Django 4.1.2 on 2023-04-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Done',
            field=models.BooleanField(default=False),
        ),
    ]
